---
namespace: nsls2
name: general
version: 1.0.0
readme: README.md
authors:
  - "Stuart B. Wilkins <swilkins@bnl.gov>"
description: Ansible collection for NSLS-II general functions
license:
  - "BSD-3-Clause"
license_file: "LICENSE"
tags: [infrastructure]
# dependencies: {}
repository: http://github.com/nsls2/nsls2.general
documentation: http://docs.nsls2.bnl.gov
homepage: http://www.bnl.gov/nsls2
issues: https://github.com/NSLS2/nsls2.general/issues
# build_ignore: []
